sudo: false

addons:
  apt:
    packages:
    - time

language: node_js

node_js:
  - "5.2.0"

cache:
  directories:
    - node_modules

notifications:
  email: false

script:
  - COVERAGE=true make

after_success:
  - node_modules/.bin/codecov
  - make release
